language: minimal

services:
  - docker

install: true

before_script:
  # Fetch master to decide what needs to be rebuilt:
  - git remote set-branches --add origin master
  - git fetch

script:
  # build docker images:
  - make build
  # push docker images to registry if master branch:
  - make push -e CURRENT_BRANCH="$TRAVIS_BRANCH" -e ONLY_BRANCH="master"
