version: '2.3'
services:

  build-images:
    build:
      context: ./docker-build
    env_file:
      - ./defaults.env
    volumes:
      - .:/work
      - /var/run/docker.sock:/var/run/docker.sock

  push-images:
    build:
      context: ./docker-push
    environment:
      - CI_REGISTRY_USER
      - CI_REGISTRY_PASSWORD
    volumes:
      - .git:/work/.git
      - /var/run/docker.sock:/var/run/docker.sock
