version: '2.4'
services:

  build-images:
    build:
      context: ./docker-build
    env_file:
      - ./defaults.env
    environment:
      - DRY_RUN
      - IMAGES
      - CACHE
      - NO_PULL
    volumes:
      - .:/work
      - /var/run/docker.sock:/var/run/docker.sock


  test-images:
    image: 7val/docker-test
    environment:
      - IMAGES
    volumes:
      - .:/work
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - test

  push-images:
    build:
      context: ./docker-push
    environment:
      - DRY_RUN
      - CI_REGISTRY_PASSWORD
      - CI_REGISTRY_USER
      - IMAGES
    volumes:
      - .:/work
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  test:
    name: test
