version: '2.3'
services:

  wordpress:
    container_name: avenga-wp
    extends:
      file: example/docker-compose.yml
      service: wordpress
    build: .
    ports:
      - 8008:80
    depends_on:
      - mysql
    networks:
      - test

  mysql:
    extends:
      file: example/docker-compose.yml
      service: mysql
    networks:
      - test

networks:
  test:
    external:
      name: test
