version: '2.3'
services:
  test:
    extends:
      file: example/docker-compose.ops.yml
      service: deploy-test
    environment:
      DRY_RUN: 1
      RANCHER_SAVE_OUTPUT_DIR: /temp
    volumes:
      - ./example/temp:/temp
