version: '2.3'
services:
  deploy-test:
    build:
      context: ./deployment
    env_file:
      - environments/app.default.env
      - environments/rancher.default.env
      - environments/test/rancher.env
      - environments/test/app.env
    environment:
      ENVIRONMENT: "test"
      # If not set all the services will be deployed:
      SERVICE: "hello-world"
      SETUP_VOLUMES: 1
    volumes:
      - ./environments:/environments
